language: python

python:
- "3.7"
- "3.8"
- "3.9"

before_install:
  - python --version
  - pip --version
  - pip install --upgrade setuptools numpy pip

install:
  - pip install -v .
  - pip list

script:
  - pytest -Wignore
