# pytest.ini
[pytest]
minversion = 6.0
addopts = -ra -q
testpaths =
    tests
filterwarnings =
    error
    ignore::pytest.PytestUnknownMarkWarning
    ignore:datetime.datetime.utcfromtimestamp:DeprecationWarning
    ignore:co_lnotab:DeprecationWarning
    ignore:Passing unrecognized arguments:DeprecationWarning
    ignore:unclosed file <_io\.BufferedReader.*?de421\.bsp:ResourceWarning
    ignore:numpy.ndarray size changed:RuntimeWarning
