name: Build sphinx documentation

on:
  workflow_call: {}

jobs:
  sphinx-build:
    runs-on: ubuntu-latest
    name: Build sphinx documentation
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install sphinx
        run: pip install sphinx
      - name: Build documentation
        run: sphinx-build -v -b html -n doc/source doc/build
      - name: Upload documentation
        uses: actions/upload-pages-artifact@v3
        with:
          path: doc/build/
