name: Build sphinx documentation

on: workflow_call

jobs:
  sphinx-build:
    runs-on: ubuntu-latest
    name: Build sphinx documentation
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install sphinx
        run: pip install sphinx sphinx-autoapi matplotlib
      - name: Build documentation
        run: python -m sphinx --verbose --builder html --nitpicky --fail-on-warning doc/source doc/build
      - name: Check links
        run: python -m sphinx --verbose --builder linkcheck --nitpicky --fail-on-warning doc/source doc/linkcheck
      - name: Upload documentation
        uses: actions/upload-pages-artifact@v3
        with:
          path: doc/build/
