on:
  push:
    inputs:
      name:
        description: 'Artifact name'
        required: false
        default: 'github-pages'
      path:
        description: "Path of the directory containing the static assets."
        required: true
        default: "doc/build/"
      retention-days:
        description: "Duration after which artifact will expire in days."
        required: false
        default: "1"

jobs:
  run_tests:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install sphinx
        run: pip install sphinx
      - name: Build documentation
        run: sphinx-build -v -b html -W --keep-going -n doc/source doc/build
      - name: Test build success
        run: tail doc/build/index.html
      - name: Archive documentation
        shell: sh
        run: |
          tar \
            --dereference --hard-dereference \
            --directory "$INPUT_PATH" \
            -cvf "$RUNNER_TEMP/artifact.tar" \
            --exclude=.git \
            --exclude=.github \
            .
        env:
          INPUT_PATH: ${{ inputs.path }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.name }}
          path: ${{ runner.temp }}/artifact.tar
          retention-days: ${{ inputs.retention-days }}
          if-no-files-found: error
