name: Build sphinx

on:
  workflow_call: {}

jobs:
  sphinx:
    runs-on: ubuntu-latest
    name: Build sphinx
    steps:
      - name: Debug log
        run: |
          pwd
          ls
          ls ..
      - name: Install sphinx
        run: pip install sphinx
      - name: Build documentation
        run: sphinx-build -v -b html -n doc/source doc/build
      - name: Upload documentation
        uses: actions/upload-pages-artifact@v2
        with:
          path: doc/build/
