name: Test workflow

on:
  push:
    branches:
      - "**"
      - "!master"

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Installation
        run: pip install .
      - name: Install test framework
        run: pip install pytest
      - name: Testing
        run: pytest
      - name: Debug log
        run: |
          pwd
          ls
          ls ..
      - name: Build sphinx
        uses: ./.github/workflows/sphinx.yml
