name: Test package

on:
  workflow_call: {}

jobs:
  sphinx:
    runs-on: ubuntu-latest
    name: Run pytest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install package
        run: pip install .
      - name: Install pytest
        run: pip install pytest
      - name: Run pytest
        run: pytest
