name: Check version

on: workflow_call

jobs:
  test:
    runs-on: ubuntu-latest
    name: Check version statements
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Echo version
        run: |
          VERSION_LINE=$(grep -E "__version__ = '([0-9]+\.[0-9]+\.[0-9]+)'" "ladim/__init__.py")
          VERSION_STRING=$(echo "$VERSION_LINE" | grep -oE "[0-9]+\.[0-9]+\.[0-9]+")
          echo "$VERSION_STRING"
