# Runs unit tests and integration tests upon updates to feature branches

name: Feature branch update

on:
  push:
    branches:
      - "**"
      - "!master"
      - "!devel"

jobs:
  run_pytest:
    uses: ./.github/workflows/action_pytest.yml
