name: Deploy main branch


on:
  workflow_dispatch: {}
  push:
    branches:
      - master


jobs:
  deploy_pypi:
    uses: ./.github/workflows/action_pypi_deploy.yml
  deploy_sphinx:
    uses: ./.github/workflows/action_sphinx_deploy.yml
